#-------------------------------------------------------------------------------
# Copyright (C) 2018 Tiago R. Muck <tmuck@uci.edu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

##################################################################
# Aggregates traces generated by trace_one.sh
# Should be given the same parameters used for trace_one.sh
# Results are saved at $TRACE_OUTPUT_DIR-$RTS_ARCH-$RTS_PLAT
#
# This script needs idle powers collected in the target platform
# saved at $TRACE_OUTPUT_DIR-$RTS_ARCH-$RTS_ARCH/idle_power
# If not available, get_idle_power.sh is run collect them
##################################################################

TRACED_CORE=$1
shift
TRACE_FREQUENCY=$1
shift
TRACED_PROGRAM=$1
shift
TRACED_PROGRAM_ARGS="$@"

# Source the files we need
source $SPARTA_SCRIPTDIR/runtime/common.sh

OUTPUT_NAME=$(basename $TRACED_PROGRAM)

PARSED_TRACES_DIR=$TRACE_OUTPUT_DIR-$RTS_ARCH-$RTS_PLAT
mkdir -p $PARSED_TRACES_DIR
RAW_OUTPUT_DIR=$PARSED_TRACES_DIR/$OUTPUT_NAME--raw--$TRACED_CORE--$TRACE_FREQUENCY.csv
mkdir -p $RAW_OUTPUT_DIR

OUTPUT_NAME_TOTAL=$PARSED_TRACES_DIR/$OUTPUT_NAME--trace_total--$TRACED_CORE--$TRACE_FREQUENCY.csv
OUTPUT_NAME_PERIODIC=$PARSED_TRACES_DIR/$OUTPUT_NAME--trace_periodic--$TRACED_CORE--$TRACE_FREQUENCY.csv

#copies (presanitizedcsv are generated only by training scripts)
cp $TRACE_OUTPUT_DIR/*.txt $RAW_OUTPUT_DIR
cp $TRACE_OUTPUT_DIR/*.csv $RAW_OUTPUT_DIR
cp $TRACE_OUTPUT_DIR/*.presanitizedcsv $RAW_OUTPUT_DIR >/dev/null 2>&1 

#ajust idle power, but first makes sure the file is there
IDLE_POWER_DIR=$PARSED_TRACES_DIR/idle_power
if [ ! -d $IDLE_POWER_DIR ]
then
    echo "Idle power directory $IDLE_POWER_DIR does not exist"
    echo "Running get_idle_power.sh"
    sh $SPARTA_SCRIPTDIR/tracing/get_idle_power.sh $IDLE_POWER_DIR
    if [ ! -d $IDLE_POWER_DIR ]
    then
        echo "Error geting idle power !"
        exit 1
    fi
fi

# now ajusts
# power is ajusted for the periodic traces only
FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.csv | xargs)
for file in $FILES 
do
    cp $file $file.prepowerajustcsv
    python3 $SPARTA_SCRIPTDIR/tracing/remove_idle_power.py --srcfile $file --destfile $file --idlepowerdir $IDLE_POWER_DIR
done

#aggregates the files from multiples runs
FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.csv | xargs)
python3 $SPARTA_SCRIPTDIR/tracing/trace_agg-periodic.py --srcfiles $FILES --destfile $OUTPUT_NAME_PERIODIC

