#-------------------------------------------------------------------------------
# Copyright (C) 2018 Tiago R. Muck <tmuck@uci.edu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

##################################################################
# Aggregates traces generated by trace_one.sh
# Should be given the takes the path to a *.raw directory and
# generates a *.csv file with the aggregated trace.
#
# This script needs idle powers collected in the target platform
# saved at $TRACE_OUTPUT_DIR-$RTS_ARCH-$RTS_ARCH/idle_power
# If not available, get_idle_power.sh is run collect them.
#
# Usage:
#   trace_parse.sh <raw_trace_dir>
##################################################################

RAW_OUTPUT_DIR=$1

if [[ $RAW_OUTPUT_DIR != *.raw ]]
then
    echo "Invalid trace path $RAW_OUTPUT_DIR"
    echo "Expect path ending with .raw"
    exit 1
fi
if [ ! -d $RAW_OUTPUT_DIR ]
then
    echo "$RAW_OUTPUT_DIR is not a valid directory"
    exit 1
fi

# Source the files we need
source $MARS_SCRIPTDIR/runtime/common.sh


# The paths
PARSED_TRACES_DIR=$(dirname $RAW_OUTPUT_DIR)
_RAW_OUTPUT_DIR=$(basename $RAW_OUTPUT_DIR .raw)
OUTPUT_TRACE_NAME=$PARSED_TRACES_DIR/$_RAW_OUTPUT_DIR.csv

# Ajust idle power, but first makes sure the file is there
IDLE_POWER_DIR=$PARSED_TRACES_DIR/idle_power
if [ ! -d $IDLE_POWER_DIR ]
then
    echo "Idle power directory $IDLE_POWER_DIR does not exist !"
    echo "It should've been generated while tracing'"
    exit 1
fi
if [ ! -f $IDLE_POWER_DIR.json ]
then
    echo "Idle power file $IDLE_POWER_DIR.json does not exist"
    echo "Parsing idle powers..."
    python3 $MARS_SCRIPTDIR/tracing/make_idle_power.py $IDLE_POWER_DIR
    if [ ! -f $IDLE_POWER_DIR.json ]
    then
        echo "Error parsing idle power !"
        exit 1
    fi
fi

# Now ajusts power.
# Power is ajusted for the periodic traces only.
# Also if we have sanitized files produced by
# scripts/training/training_trace_parse.sh
# we use those instead of raw csvs
_RAW_OUTPUT_DIR=$(basename $RAW_OUTPUT_DIR)
echo "Ajusting idle power for $_RAW_OUTPUT_DIR/*.$TP_SANITIZE_EXT"
FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.$TP_SANITIZE_EXT 2>/dev/null | xargs)
FILES_EXT=$TP_SANITIZE_EXT
RESAMPLING="--noresampling"
if [ -z "$FILES" ]
then
    echo "No sanitized traces. Ajusting idle power for $_RAW_OUTPUT_DIR/*.csv"
    FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.csv | xargs)
    FILES_EXT="csv"
    RESAMPLING=""
    if [ -z "$FILES" ]
    then
        echo "Error! No valid traces found at $RAW_OUTPUT_DIR"
        exit 1
    fi
fi
for file in $FILES 
do
    destfile="${file/%.$FILES_EXT/.$TP_POWAJUST_EXT}"
    python3 $MARS_SCRIPTDIR/tracing/remove_idle_power.py --srcfile $file --destfile $destfile --idlepowers $IDLE_POWER_DIR.json
done

#aggregates the files from multiples runs
_OUTPUT_TRACE_NAME=$(basename $OUTPUT_TRACE_NAME)
echo "Aggregating $_RAW_OUTPUT_DIR/*.$TP_POWAJUST_EXT into $_OUTPUT_TRACE_NAME"
FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.$TP_POWAJUST_EXT | xargs)
if [ -z "$FILES" ]
then
    echo "Error! No power ajusted traces found at $RAW_OUTPUT_DIR"
    exit 1
fi
python3 $MARS_SCRIPTDIR/tracing/trace_agg-periodic.py $RESAMPLING --srcfiles $FILES --destfile $OUTPUT_TRACE_NAME

