##################################################################
# Aggregates traces generated by trace_one.sh
# Should be given the same parameters used for trace_one.sh
#################################################################

TRACED_CORE=$1
shift
TRACE_FREQUENCY=$1
shift
TRACED_PROGRAM=$1
shift
TRACED_PROGRAM_ARGS="$@"

# Source the files we need
source $SPARTA_SCRIPTDIR/runtime/common.sh

OUTPUT_NAME=$(basename $TRACED_PROGRAM)

PARSED_TRACES_DIR=$TRACE_OUTPUT_DIR"_parsed"
mkdir -p $PARSED_TRACES_DIR
RAW_OUTPUT_DIR=$PARSED_TRACES_DIR/$OUTPUT_NAME--raw
mkdir -p $RAW_OUTPUT_DIR

OUTPUT_NAME_TOTAL=$PARSED_TRACES_DIR/$OUTPUT_NAME--trace_total--$TRACED_CORE--$TRACE_FREQUENCY.csv
OUTPUT_NAME_PERIODIC=$PARSED_TRACES_DIR/$OUTPUT_NAME--trace_periodic--$TRACED_CORE--$TRACE_FREQUENCY.csv

#copies
cp $TRACE_OUTPUT_DIR/*.txt $RAW_OUTPUT_DIR
cp $TRACE_OUTPUT_DIR/*.csv $RAW_OUTPUT_DIR

#parse
FILES=$(ls $RAW_OUTPUT_DIR/trace_result*.csv | xargs)
python3 $SPARTA_SCRIPTDIR/tracing/trace_agg.py --srcfiles $FILES --destfile $OUTPUT_NAME_TOTAL

FILES=$(ls $RAW_OUTPUT_DIR/periodic_trace_result*.csv | xargs)
python3 $SPARTA_SCRIPTDIR/tracing/trace_agg-periodic.py --srcfiles $FILES --destfile $OUTPUT_NAME_PERIODIC

