version: "3.2"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "${USER_ID}:${GROUP_ID}"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '3000:3000'
    links:
        - prometheus
    volumes:
        - ./grafana:/var/lib/grafana
        - ./config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
        monitoring:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
      - '--web.enable-admin-api'
    user: "${USER_ID}:${GROUP_ID}"
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:

networks:
  monitoring:
    external:
      name: monitoring

  default:
    driver: bridge
